---
steps:
  ##################################################
  ########## BUILD
  ##################################################
  - id: 'Build emailservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/emailservice
      - --destination=gcr.io/$PROJECT_ID/emailservice
      - --cache=true
      - --single-snapshot=true

  - id: 'Build productcatalogservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/productcatalogservice
      - --destination=gcr.io/$PROJECT_ID/productcatalogservice
      - --cache=true
      - --single-snapshot=true

  - id: 'Build recommendationservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/recommendationservice
      - --destination=gcr.io/$PROJECT_ID/recommendationservice
      - --cache=true
      - --single-snapshot=true

  - id: 'Build shippingservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/shippingservice
      - --destination=gcr.io/$PROJECT_ID/shippingservice
      - --cache=true
      - --single-snapshot=true

  - id: 'Build checkoutservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/checkoutservice
      - --destination=gcr.io/$PROJECT_ID/checkoutservice
      - --cache=true
      - --single-snapshot=true

  - id: 'Build paymentservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/paymentservice
      - --destination=gcr.io/$PROJECT_ID/paymentservice
      - --cache=true
      - --single-snapshot=true

  - id: 'Build currencyservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/currencyservice
      - --destination=gcr.io/$PROJECT_ID/currencyservice
      - --cache=true
      - --single-snapshot=true

  - id: 'Build cartservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/cartservice
      - --destination=gcr.io/$PROJECT_ID/cartservice
      - --cache=true
      - --single-snapshot=true

  - id: 'Build frontend'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/frontend
      - --destination=gcr.io/$PROJECT_ID/frontend
      - --cache=true
      - --single-snapshot=true

  - id: 'Build loadgenerator'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/loadgenerator
      - --destination=gcr.io/$PROJECT_ID/loadgenerator
      - --cache=true
      - --single-snapshot=true

  - id: 'Build adservice'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=./third-party/google-microservices/src/adservice
      - --destination=gcr.io/$PROJECT_ID/adservice
      - --cache=true
      - --single-snapshot=true

  ##################################################
  ########### DEPLOY
  ##################################################
  - id: 'Deploy microservice images to GKE'
    name: 'gcr.io/cloud-builders/gke-deploy'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        ./bin/kustomize build -o ./kustomize-output.yml && \
        /gke-deploy run -n $_NAMESPACE -c $_CLUSTER -l $_LOCATION \
        -o output-microservices -f ./kustomize-output.yml

  - id: 'Apply istio manifests'
    name: 'gcr.io/cloud-builders/gke-deploy'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        /gke-deploy run -n $_NAMESPACE -c $_CLUSTER -l $_LOCATION \
        -o output-istio -f ./third-party/google-microservices/istio-manifests/

timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'
