---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./third-party/google-manifests/kubernetes/adservice.yaml
- ./third-party/google-manifests/kubernetes/cartservice.yaml
- ./third-party/google-manifests/kubernetes/checkoutservice.yaml
- ./third-party/google-manifests/kubernetes/currencyservice.yaml
- ./third-party/google-manifests/kubernetes/emailservice.yaml
- ./third-party/google-manifests/kubernetes/frontend.yaml
- ./third-party/google-manifests/kubernetes/loadgenerator.yaml
- ./third-party/google-manifests/kubernetes/paymentservice.yaml
- ./third-party/google-manifests/kubernetes/productcatalogservice.yaml
- ./third-party/google-manifests/kubernetes/recommendationservice.yaml
- ./third-party/google-manifests/kubernetes/shippingservice.yaml
- ./third-party/google-manifests/kubernetes/redis.yaml
images:
- name: adservice
  newName: gcr.io/gke-demo-1577812932/adservice
- name: cartservice
  newName: gcr.io/gke-demo-1577812932/cartservice
- name: checkoutservice
  newName: gcr.io/gke-demo-1577812932/checkoutservice
- name: currencyservice
  newName: gcr.io/gke-demo-1577812932/currencyservice
- name: emailservice
  newName: gcr.io/gke-demo-1577812932/emailservice
- name: frontend
  newName: gcr.io/gke-demo-1577812932/frontend
- name: loadgenerator
  newName: gcr.io/gke-demo-1577812932/loadgenerator
- name: paymentservice
  newName: gcr.io/gke-demo-1577812932/paymentservice
- name: productcatalogservice
  newName: gcr.io/gke-demo-1577812932/productcatalogservice
- name: recommendationservice
  newName: gcr.io/gke-demo-1577812932/recommendationservice
- name: shippingservice
  newName: gcr.io/gke-demo-1577812932/shippingservice
