apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./third-party/google-microservices/kubernetes-manifests/adservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/cartservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/checkoutservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/currencyservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/emailservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/frontend.yaml
- ./third-party/google-microservices/kubernetes-manifests/loadgenerator.yaml
- ./third-party/google-microservices/kubernetes-manifests/paymentservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/productcatalogservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/recommendationservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/shippingservice.yaml
- ./third-party/google-microservices/kubernetes-manifests/redis.yaml
images:
- name: adservice
  newName: gcr.io/gke-demo-muirtj/adservice
- name: cartservice
  newName: gcr.io/gke-demo-muirtj/cartservice
- name: checkoutservice
  newName: gcr.io/gke-demo-muirtj/checkoutservice
- name: currencyservice
  newName: gcr.io/gke-demo-muirtj/currencyservice
- name: emailservice
  newName: gcr.io/gke-demo-muirtj/emailservice
- name: frontend
  newName: gcr.io/gke-demo-muirtj/frontend
- name: loadgenerator
  newName: gcr.io/gke-demo-muirtj/loadgenerator
- name: paymentservice
  newName: gcr.io/gke-demo-muirtj/paymentservice
- name: productcatalogservice
  newName: gcr.io/gke-demo-muirtj/productcatalogservice
- name: recommendationservice
  newName: gcr.io/gke-demo-muirtj/recommendationservice
- name: shippingservice
  newName: gcr.io/gke-demo-muirtj/shippingservice
