---
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: emailservice
    context: ./third-party/google-microservices/src/emailservice
  - image: productcatalogservice
    context: ./third-party/google-microservices/src/productcatalogservice
  - image: recommendationservice
    context: ./third-party/google-microservices/src/recommendationservice
  - image: shippingservice
    context: ./third-party/google-microservices/src/shippingservice
  - image: checkoutservice
    context: ./third-party/google-microservices/src/checkoutservice
  - image: paymentservice
    context: ./third-party/google-microservices/src/paymentservice
  - image: currencyservice
    context: ./third-party/google-microservices/src/currencyservice
  - image: cartservice
    context: ./third-party/google-microservices/src/cartservice
  - image: frontend
    context: ./third-party/google-microservices/src/frontend
  - image: loadgenerator
    context: ./third-party/google-microservices/src/loadgenerator
  - image: adservice
    context: ./third-party/google-microservices/src/adservice
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./third-party/google-microservices/kubernetes-manifests/**.yaml
profiles:
# This is not used by default. To use it, run:
#     skaffold run -p gcb
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s
