---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "${app_name}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/${github_demo_owner}/${github_demo_reponame}"
    targetRevision: master
    path: "${manifests_dir}"

    kustomize:
      images:
      - "adservice=gcr.io/${project}/adservice"
      - "cartservice=gcr.io/${project}/cartservice"
      - "checkoutservice=gcr.io/${project}/checkoutservice"
      - "currencyservice=gcr.io/${project}/currencyservice"
      - "emailservice=gcr.io/${project}/emailservice"
      - "paymentservice=gcr.io/${project}/paymentservice"
      - "productcatalogservice=gcr.io/${project}/productcatalogservice"
      - "recommendationservice=gcr.io/${project}/recommendationservice"
      - "shippingservice=gcr.io/${project}/shippingservice"
      - "frontend=gcr.io/${project}/frontend"

  destination:
    server: "${k8s_cluster_url}"
    namespace: "${app_namespace}"

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
