---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - ./third-party/rollout-transform.yaml

resources:
  - adservice.yaml
  - cartservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontend.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - shippingservice.yaml
  - redis.yaml
