apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: adservice
  newName: gcr.io/gke-demo-1577719075/adservice
- name: cartservice
  newName: gcr.io/gke-demo-1577719075/cartservice
- name: checkoutservice
  newName: gcr.io/gke-demo-1577719075/checkoutservice
- name: currencyservice
  newName: gcr.io/gke-demo-1577719075/currencyservice
- name: emailservice
  newName: gcr.io/gke-demo-1577719075/emailservice
- name: frontend
  newName: gcr.io/gke-demo-1577719075/frontend
- name: paymentservice
  newName: gcr.io/gke-demo-1577719075/paymentservice
  newTag: 306fa63
- name: productcatalogservice
  newName: gcr.io/gke-demo-1577719075/productcatalogservice
- name: recommendationservice
  newName: gcr.io/gke-demo-1577719075/recommendationservice
- name: shippingservice
  newName: gcr.io/gke-demo-1577719075/shippingservice
